// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlipController from "./flip_controller"
application.register("flip", FlipController)

import ProgressController from "./progress_controller"
application.register("progress", ProgressController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
