// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlashcardColorController from "./flashcard_color_controller"
application.register("flashcard-color", FlashcardColorController)

import FlipController from "./flip_controller"
application.register("flip", FlipController)

import ProgressController from "./progress_controller"
application.register("progress", ProgressController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TasksCardsController from "./tasks_cards_controller"
application.register("tasks-cards", TasksCardsController)
